"""empty message

Revision ID: fa3bd343369b
Revises: a943c9bb9045
Create Date: 2021-03-16 11:18:05.999048

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'fa3bd343369b'
down_revision = 'a943c9bb9045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_index('idx_locations_geom', table_name='locations')
    op.drop_constraint('locations_shift_id_fkey', 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'shifts', ['shift_id'], ['shift_id'])
    op.add_column('shifts', sa.Column('shift_id', sa.Integer(), nullable=False))
    op.drop_column('shifts', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('shifts', 'shift_id')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key('locations_shift_id_fkey', 'locations', 'shifts', ['shift_id'], ['id'])
    op.create_index('idx_locations_geom', 'locations', ['geom'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
